name: Build Flutter Apps

on:
  - push

jobs:
  build_ios:
    runs-on: macos-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - uses: cedvdb/action-flutter-build-ios@v1
        with:
          # always use --export-options-plist=ios/GithubActionsExportOptions.plist
          build-cmd: flutter build ipa --release --export-options-plist=iosApp/GithubActionsExportOptions.plist
          # certificate-base64: ${{ secrets.IOS_BUILD_CERTIFICATE_BASE64 }}
          # certificate-password: ${{ secrets.IOS_BUILD_CERTIFICATE_PASSWORD }}
          # provisioning-profile-base64: ${{ secrets.IOS_MOBILE_PROVISIONING_PROFILE_BASE64 }}
          # keychain-password: ${{ secrets.IOS_GITHUB_KEYCHAIN_PASSWORD }}

      - name: Archive IPA
        uses: actions/upload-artifact@v4
        with:
          name: release-ipa
          # Try running the build locally with the build command to be sure of this path
          path: build/ios/ipa/tdot_gkr.ipa